# Generated by Django 4.2.30 on 2026-05-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=123, max_length=400),
            preserve_default=False,
        ),
    ]
