# Generated by Django 4.2.30 on 2026-07-20 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('GROUP', 'Group')], default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 20, 8, 4, 6, 312221, tzinfo=datetime.timezone.utc)),
        ),
    ]
