# Generated by Django 4.2.30 on 2026-05-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='static/media/users/')),
                ('password', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=0)),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField()),
                ('last_logout', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/media/posts/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=1)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('views', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_network.user')),
            ],
        ),
    ]
