# Generated by Django 4.2.30 on 2026-05-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
