# Generated by Django 4.2.30 on 2026-05-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Network', '0002_remove_post_user'),
        ('auth_network', '0002_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
