# Generated by Django 4.2.30 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_network', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, unique=True)),
                ('photo', models.ImageField(upload_to='static/media/users/')),
                ('password', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=0)),
                ('registered_time', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
