# Generated by Django 4.2.30 on 2026-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_network', '0006_user_interests_user_playlists_user_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.TextField(default='[]'),
        ),
    ]
